
version: 2

models:
  - name: dim_season_drivers_teams
    description: "Dimension table for season, drivers and teams"
    columns:
      - name: season_driver_team_key
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
  - name: fct_laps
    columns:
      - name: lap_id
        data_tests:
          - unique
          - not_null
      - name: season_driver_team_key
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_season_drivers_teams')
                field: season_driver_team_key
  - name: fct_results
    columns:
      - name: result_id
        data_tests:
          - unique
          - not_null
      - name: season_driver_team_key
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_season_drivers_teams')
                field: season_driver_team_key